version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: ${TENANT}_db
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - ${TENANT}_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}

volumes:
  biopharma_data:
  kmh_data:
  wake_data:
